### ISSUE TITLE
Data transfer through network on MacOS

### ISSUE THREAD

**Issue by tmptrash** [tmptrash/jevo#55]
Под MacOS данные по сети передаются очень медленно. Нужно проверить на других типах девайсов с этой ОС чтобы исключить проблемы с настройками сети на конкретном компьютере. Проблема состоит в том, что сервер отправляет данные на клиент с помощью реквестов в "быстром" режиме, а клиент принимает их очень медленно (примерно раз в секунду). А именнно, на стороне клиента в модуле RemoteWorldRT функция _onDot() вызывается очень редко.

Update: Мы разобрались в чем проблема - то не сеть, это отрисовка на стороне визуалайзера. Конкретно это метод dot(). Я говорил с разработчиком GR.jl и единственное, что он посоветовал это либо собирать точки в массив вот так:

``` julia
using GR

xmin = -3
xmax = 3
ymin = -3
ymax = 3

resx = resy = 300

setviewport(0, 1, 0, 1)
setwindow(xmin, xmax, ymin, ymax)

cells = zeros(Int32, resx, resy)

while true
    x, y, color = randn(), randn(), round(Int, rand() * 255)
    ix = round(Int, (resx - 1) * (x - xmin) / (xmax - xmin)) + 1
    iy = round(Int, (resy - 1) * (y - ymin) / (ymax - ymin)) + 1
    if 1 <= ix <= resx && 1 <= iy <= resy
        println("$ix, $iy, $color")
        cells[ix, iy] = 1000 + color
    end
    clearws()
    setcolormap(13)
    cellarray(xmin, xmax, ymin, ymax, resx, resy, cells)
    updatews()
end
```

второй совет: " In this example, each point is shown as it "arrives". To avoid flickering, you can enable double buffering".

``` julia
export GKS_DOUBLE_BUF=1
```

**Comment by mekhovov** [comment]
looks like `export GKS_DOUBLE_BUF=1` doesn't work 👎

**Comment by tmptrash** [comment]
Можно попробовать пингануть разработчика еще раз. Возможно что-то поменялось со времен создания этой баги. Его можно найти в чате [здесь](https://gitter.im/jheinen/GR.jl?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
