### ISSUE TITLE
No backup folder error

### ISSUE THREAD

**Issue by tmptrash** [tmptrash/jevo#73]
INFO: Server created: 127.0.0.1:2010
INFO: Server created: 127.0.0.1:2011
INFO: Recovering from backup:
WARNING: Backup folder doesn't exist: backup
ERROR: LoadError: MethodError: Cannot `convert` an object of type String to an object of type Array{String,1}
This may have arisen from a call to the constructor Array{String,1}(...),
since type constructors fall back to convert methods.
 in _removeNew(::ManagerTypes.ManagerData) at e:\my\jevo\src\manager\ManagerBackup.jl:168
 in recover(::ManagerTypes.ManagerData) at e:\my\jevo\src\manager\ManagerBackup.jl:35
 in main() at e:\my\jevo\src\AppManager.jl:26
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading e:\my\jevo\src\AppManager.jl, in expression starting on line 36
_removeBrokenBackup(), time: 1.475525471992e9, stamp: 1.475525468231e9, period: 60.0
last file:

**Comment by rkxtd** [comment]
Fixed https://github.com/tmptrash/jevo/commit/bb94464ea30ccb14892dc080d4a168e972bb1adf
